[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=61.0",
    "setuptools_scm[toml]>=7.0.0",
    "wheel",
    "lark"
]

[tool.setuptools_scm]
version_scheme = "no-guess-dev"
write_to = "named_einsum/version.py"
